[build]
  base = "todo-list"
  command = "npm run build"
  publish = "todo-list/build"

[build.environment]
  NODE_VERSION = "18.20.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
